<?xml version="1.0" encoding="UTF-8"?>
<urlset
        xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

    <url>
        <loc>http://overscore.kr/</loc>
    </url>
    <url>
        <loc>http://overscore.kr/search?name=</loc>
    </url>
    <url>
        <loc>http://overscore.kr/favorite</loc>
    </url>
    <url>
        <loc>http://overscore.kr/feedback</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=9709</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=9694</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=9666</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=95526</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=94411</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=93129</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=93123</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=93093</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=93085</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=93037</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=92966</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=87915</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=87512</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=86055</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=8346</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=80479</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=80170</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=77404</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=7523</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=7522</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=7448</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=7323</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=71839</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=71299</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=69100</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=6790</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=6551</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=6538</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=6412</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=6271</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=59793</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=59005</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=58900</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=57334</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=56892</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=5625</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=5439</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=50870</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=49840</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=47475</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=4744</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=45996</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=4464</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=40158</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=39397</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=3867</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=3813</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=38096</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=36819</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=3219</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=31222</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=30426</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=3027</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=28332</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=27915</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=26720</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=26025</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=25772</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=25576</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=25470</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=25312</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=24916</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=22959</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=22755</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=2121</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=19084</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=1868</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=1854</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=1822</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=17169</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=16751</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=1662</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=16006</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=15453</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=1494</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=14807</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=14468</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=14027</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=1268</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=12494</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=12314</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=11357</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=11294</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=10629</loc>
    </url>
    <url>
        <loc>http://overscore.kr/profile?userId=10481</loc>
    </url>

</urlset>